
export PYENV_ROOT="${HOME}/.pyenv"

if [ -d "${PYENV_ROOT}" ]; then
  export PATH="${PYENV_ROOT}/bin:${PATH}"
  eval "$(pyenv init -)"
fi
export VIM_HOME=$(brew --prefix vim)
export GIT_HOME=$(brew --prefix git)
export PATH="$GIT_HOME/bin:$VIM_HOME/bin:/usr/local/opt/openssl@1.1/bin:$PATH"


LDFLAGS=-L/usr/local/opt/openssl@1.1/lib
CPPFLAGS=-I/usr/local/opt/openssl@1.1/include

if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

export PYENV_VIRTUALENV_DISABLE_PROMPT=1
