- hosts: wxnacy
  remote_user: root
  tasks:
  - name: git pull /www/wxnacy
    shell: |
        git fetch
        git checkout '{{tag_name}}'
        # ./deploy_hexo.sh '{{tag_name}}'
    args:
      chdir: /www/wxnacy.github.io
    register: result
  - name: Show debug
    debug: var=result verbosity=0

