- hosts: wxnacy
  remote_user: root
  tasks:
  - name: deploy wxnacy.github.io nginx
    shell: git pull && git submodule update --remote hexo/themes/yilia
    args:
      chdir: /www/wxnacy.github.io
  # - name: deploy wxnacy.github.io python
    # shell: ./deploy_api.sh '{{tag_name}}'
    # args:
      # chdir: ~/wxnacy.github.io
