#!/usr/bin/env expect

# echo 'export MYSQL_PROD_USER=your_prod_user' >> ~/.bash_profile                                                                                         master?
# echo 'export MYSQL_PROD_PASSWORD=your_prod_password' >> ~/.bash_profile                                                                                master?
# echo 'export MYSQL_PROD_HOST=your_prod_host' >> ~/.bash_profile
# source ~/.bash_profile


set timeout 10

if { $argc == 0 } {
    set ENV local
}
if { $argc > 0 } {
    set ENV [lindex $argv 0]
}
if { $ENV == "local" } {
    set name root
    set password wxnacy
    set host localhost
}
if { $ENV == "prod" } {
    set name $env(MYSQL_PROD_USER)
    set password $env(MYSQL_PROD_PASSWORD)
    set host $env(MYSQL_PROD_HOST)
}

spawn sh -c "mysql -u$name -p -h ${host} --tee=/data/log/mysql/`date +%Y-%m-%d`.log"
expect "*assword:*"
send "$password\r"
interact
# expect eof
