site_name: 面试宝典
site_dir: ../hexo/public/audition

nav:
    - 面试宝典: index.md
    - Python: python.md
    - 算法: algorithm.md
    - Mysql: mysql.md

theme: readthedocs
extra_javascript:
    - js/wxnacy.min.js
