# Header

menu:
  主页: /
  # 领取红包: /redpecket/
  Alfred Workflow: https://github.com/wxnacy/alfred-commands-workflow
  《Vim 练级手册》: https://vim.wxnacy.com
  常用命令: https://cmd.wxnacy.com
  代码笔记: https://notebook.wxnacy.com
  合辑: /album
  在线工具: /tool
  # 时间轴: /archives


# SubNav
subnav:
  github: "https://github.com/wxnacy"
  # weibo: "http://weibo.com/wxnacy"
  rss: "/atom.xml"
  # zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:wxnacy@gmail.com"
  #facebook: "#"
  #google: "#"
  twitter: "https://twitter.com/wxnacy"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root:

# Content

# 文章太长，截断按钮文字
excerpt_link: 阅读全文
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 最近最热
hot_acticles:

    Go 判断数组中是否包含某个 item: /2018/11/20/go-in-array/
    Vim 高级功能 vimgrep 全局搜索文件: /2017/10/13/vim-grep/
    办理北京工作居住证的一些细节: /2018/02/11/beijing-xiaolvka/
    Go 语法错误：Non-declaration statement outside function body: /2018/08/16/go-syntax-error2/
    Mac 电脑查看字体文件位置: /2019/04/03/mac-fonts-path/

# 最新文章
last_acticles:

    Alfred Workflow 命令行帮助工具: https://github.com/wxnacy/alfred-commands-workflow

# 公众号
mp_text1: '扫码关注公众号，或搜索公众号“温欣爸比”'
mp_text2: '及时获取我的最新文章'
mp_img: /images/mp.jpg

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '谢谢你请我喝咖啡'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /images/alisq.png
# 微信二维码图片地址
weixin: /images/wxsq.png

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /images/favicon.ico

#你的头像url
avatar: /images/avator.jpg

#是否开启分享
share_jia: false

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false #
changyan_conf: false #

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: false #7698847 #你的 GitHub ID
gitment_repo: 'https://github.com/wxnacy/wxnacy.github.io.git'          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  Guru99: https://www.guru99.com/
  # 友情链接2: http://localhost:4000/
  # 友情链接3: http://localhost:4000/
  # 友情链接4: http://localhost:4000/
  # 友情链接5: http://localhost:4000/
  # 友情链接6: http://localhost:4000/

aboutme: 每天看书<br>每天背单词<br>每天一篇<br>写写代码<br>听听周杰伦<br>爱爱老婆

# MathJax Support
# mathjax:
  # enable: true
  # per_page: false
  # cdn: //cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
