"===============================
" Author: wxnacy
" Email: wxnacy@gmail.com
" Create time: 
" Last Modified: 2017-08-27
" Description: 
"===============================




"==============================="
" 基本设置
"==============================="

" base
set nocompatible				"去掉对vi的兼容，让vim运行在完全模式下
syntax on    					"开启语法高亮"
set history=2003                "记录VIM历史操作的条数
set autoread					"文件在vim外修改过自动重新载入
set magic                       "magic (\m)：除了 $ . * ^ 之外其他元字符都要加反斜杠。nomagic (\M)：除了 $ ^ 之外其他元字符都要加反斜杠。
set title
set nobackup                    "去掉编辑文件时的备份 
set novisualbell                "关掉可视化响铃警报
set noerrorbells                "关掉错误警报
set visualbell t_vb=            "关掉警报 
set tm=500

" leader
let mapleader = ','
let g:mapleader = ','

" filetype
filetype on                     "开启文件类型检测
filetype plugin on              "开启插件的支持
filetype indent on              "开启文件类型相应的缩进规则
set fileformat=unix    			"设置以unix的格式保存文件"

" encoding
set encoding=utf-8              "打开文件时编码格式
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1         "vim会根据该设置识别文件编码

" set fileencoding=utf-8        在保存文件时，指定编码
set termencoding=utf-8          "终端环境告诉vim使用编码
set ffs=unix,dos,mac            "在创建文件或写入时，这三种文件格式分别决定了行末要添加什么特殊字符，而在读入文件时，又分别决定了要从行末移去什么特殊字符。
set formatoptions+=m
set formatoptions+=B

" 主题 
set background=dark       		"配色主题的色系,注意，这不是什么背景色！dark 是暗色系，light 是亮色系。
colorscheme desert              "配色主题的名称,:coloscheme 后键入<tab>可以自动补全 比较喜欢的desert,peachpuff,torte,elfload,slate 

" show 
set number						"显示行号"
set ruler						"显示当前光标行号和列
set nowrap    					"设置不折行"
set sidescroll=1                "默认设置set sidescroll=0之下，当光标到达屏幕边缘时，将自动扩展显示1/2屏幕的文本。通过使用set sidescroll=1设置，可以实现更加平滑的逐个字符扩展显示。
set showcmd						"在屏幕右下角显示未完成的命令
set showmode					"显示当前vim模式
set showmatch    				"显示匹配的括号"
set matchtime=1					"设置showmatch的效果时间，默认500ms，现在是100ms
set cursorline        			"突出显示当前行"
set cursorcolumn        		"突出显示当前列"


" search
set smartcase					"搜索时，如果输入大写，则严格按照大小写搜索，如果小写，并设置了ignorecase，则忽略大小写
set ignorecase        			"搜索时忽略大小写"
set incsearch					"搜索时及时匹配搜索内容，需要回车确认
set hlsearch        			"高亮搜索项"

" tab
set expandtab                   "将<tab>符号转变为<space>空格
set smarttab					"配合shiftwidth使用，如果设置该值，在行首键入<tab>会填充shiftwidth的数值,其他地方使用tabstop的数值，不设置的话，所有地方都是用shiftwidth数值

" indent
set autoindent                  "换行自动缩进
set smartindent                 "缩进采用c语言风格
set shiftround                  "在一般模式下键入>>整个缩进shiftwidth的长度，<<反向操作,== 可以与上一行对齐，插入模式下C-T和C-D也可以左右启动
set shiftwidth=4                "缩进的空格数
set tabstop=4                   "键入<tab>的步长
set softtabstop=4                " insert mode tab and backspace use 4 spaces
    
" status line
set statusline=%<%f\ %h%m%r%=%k[%{(&fenc==\"\")?&enc:&fenc}%{(&bomb?\",BOM\":\"\")}]\ %-14.(%l,%c%V%)\ %P
set laststatus=2   " Always show the status line - use 2 lines for the status bar


" select & complete
set selection=inclusive         "选择文本事，光标所在位置也会被选中
set selectmode=mouse,key

set scrolloff=5        			"距离顶部和底部5行"
set backspace=2					"任何情况允许使用退格键删除
set mouse=a       				"启用鼠标"



"===============================
" Python 工作环境 
"==============================
autocmd FileType python set tabstop=4 shiftwidth=4 textwidth=79 expandtab ai
autocmd BufNewFile *.py exec ":call NewPyFile()"
function! NewPyFile()
    if &filetype == 'python'
        call setline(1, "\#!/usr/bin/env python")
        call append(1, "\# -*- coding:utf-8 -*-")
        call append(2, "\# Author: wxnacy")
        call append(3, "\# Email: wxnacy@gmail.com")
        call append(4, "\# Description: ")
    endif

    normal G
    normal o
    normal o
endfunc


"===============================
" 安装插件
"===============================

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
Plugin 'Valloric/YouCompleteMe'
Plugin 'altercation/vim-colors-solarized'
colorscheme solarized
call vundle#end()            " required
