site_name: Leetcode 刷题集
site_dir: ../hexo/public/leetcode

nav:
  - 来刷题: index.md
  # - 数组:
  - 1. 两数之和: problems/1-two-sum.md
  - 2. 两数相加: problems/2-add-two-numbers.md
  - 3. 无重复字符的最长子串: problems/3-longest-substring-without-repeating-characters.md
  # - 4. 寻找两个有序数组的中位数: problems/4-median-of-two-sorted-arrays.md
  - 7. 整数反转: problems/7-reverse-integer.md

theme: readthedocs
