source ~/.bash_profile
export ZSH=${HOME}/.oh-my-zsh


ZSH_THEME="fishy"

plugins=(git python sublime)
source $ZSH/oh-my-zsh.sh

alias zshc="vim ~/.zshrc"
alias zshs="source ~/.zshrc"
alias vimc="vim ~/.vimrc"
alias bp="vim ~/.bash_profile"
alias bps="source ~/.bash_profile"

alias c="clear"
alias h="history"
