echo '.zshrc' >> /tmp/zshmsg
PS4=$'\\\011%D{%s%6.}\011%x\011%I\011%N\011%e\011'
exec 3>&2 2>/tmp/zshstart.$$.log
setopt xtrace prompt_subst
source ~/.bash_profile
export ZSH=${HOME}/.oh-my-zsh

# https://github.com/robbyrussell/oh-my-zsh/wiki/themes
# ZSH_THEME="fishy"
ZSH_THEME="bureau"

plugins=(git python sublime)
source $ZSH/oh-my-zsh.sh


# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/wxnacy/Downloads/19/12/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/wxnacy/Downloads/19/12/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/wxnacy/Downloads/19/12/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/wxnacy/Downloads/19/12/node_modules/tabtab/.completions/sls.zsh
unsetopt xtrace
exec 2>&3 3>&-
